"""add upload_id to orders

Revision ID: 9a7d3b5c8e1f
Revises: 8afd6ead93d3
Create Date: 2026-07-10 09:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a7d3b5c8e1f'
down_revision: Union[str, None] = '8afd6ead93d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('upload_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_orders_uploads', 'orders', 'uploads', ['upload_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_orders_upload_id'), 'orders', ['upload_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_upload_id'), table_name='orders')
    op.drop_constraint('fk_orders_uploads', 'orders', type_='foreignkey')
    op.drop_column('orders', 'upload_id')
    # ### end Alembic commands ###
